### PR TITLE
fix(badge): #2616

### LINKED ISSUE #2616: Badge 气泡显示数字问题
image
1.鼠标移上去后气泡没有显示完整的数字
2.建议鼠标移动到数字后在显示气泡完整数字

### PR DESCRIPTION
**Pull request by aqiusen**
closed #2616

### CODE REVIEW

File: packages/ui/badge/src/Badge.tsx [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import React, { forwardRef, useMemo, isValidElement, cloneElement } from 'react'
```
Comment (zyprepare) [inline packages/ui/badge/src/Badge.tsx:1]: 修改代码存在格式化问题

**Review by zyprepare — APPROVED** [review]
