### PR TITLE
fix(tabs): #2395

### LINKED ISSUE #2395: Tabs tab 数量过多时，activeId 设置为较后的 tab，该 tab 显示不出来
**温馨提示**

请在提交 Issue 前，先通过如下途径链接检查是否有类似的 Issue 或者问题存在，看能否找到你想要的答案：

- [issues 列表](https://github.com/XiaoMi/hiui/issues?q=label%3A4.x+label%3A%22comp%3Atabs%22)
- [FAQ 列表](https://github.com/XiaoMi/hiui/issues/1914)

**内容描述**

清晰简洁的描述您想要反馈的问题或者建议性功能。

### PR DESCRIPTION
**Pull request by zyprepare**
closed #2395

### CODE REVIEW

File: packages/ui/tabs/src/TabList.tsx [hunk 1]
```diff
@@ -140,36 +142,48 @@ export const TabList = forwardRef<HTMLDivElement | null, TabListProps>(
...
     const onClickTab = useLatestCallback((tabId: React.ReactText, event: React.MouseEvent) => {
       onTabClick?.(tabId, event)
       setActiveTabId(tabId)
       syncScrollPosition(tabId)
     })
 
+    useEffect(() => {
+      // activeId 受控模式下改变后，同步更新滚动位置
+      activeId && syncScrollPosition(activeId)
+    }, [activeId, setActiveTabId, syncScrollPosition])
```
Comment (solarjoker) [inline packages/ui/tabs/src/TabList.tsx:185]: 这里为啥要依赖 setActiveTabId？

Comment (zyprepare) [reply packages/ui/tabs/src/TabList.tsx]: 忘记去掉了，无需依赖它，已去掉。

**Review by solarjoker — APPROVED** [review]
